apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  namespace: athena
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    name: http
  selector:
    app: mysql-master 
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  namespace: athena
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 20006
    name: http
  selector:
    app: mysql-slave 
