---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-master
  namespace: athena
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-dynamic-class
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-slave
  namespace: athena
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-dynamic-class
  resources:
    requests:
      storage: 10Gi
