apiVersion: v1
kind: Service
metadata:
  name: node-ffmpeg
spec:
  selector:
    app: node-ffmpeg
  ports:
  - name: master
    port: 3000
    targetPort: 3000
  - name: api
    port: 2313
    targetPort: 2313
  - name: stream
    port: 7777
    targetPort: 7777
