apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: faiss-data
  namespace: athena
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-dynamic-class
  resources:
    requests:
      storage: 100Gi
