apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "kafka-kafka-0"
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-kafka-0
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pv-kafka-0
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "kafka-kafka-1"
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-kafka-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pv-kafka-1
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "kafka-kafka-2"
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-kafka-2
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pv-kafka-2
  resources:
    requests:
      storage: 10Gi
