apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: verifier
  namespace: athena
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verifier
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: verifier
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - 192.168.1.5
                - 192.168.1.6
      containers:
      - image: harbor.oceanai.com.cn/detector/verifier-rest:gpu
        imagePullPolicy: Always
        name: verfier
        ports:
        - containerPort: 33388
        env:
        - name: REDIS_HOST
          value: "verifier-redis"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verifier-redis
  namespace: athena
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-dynamic-class
  resources:
    requests:
      storage: 10Gi
