apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: verifier-redis
  namespace: athena
spec:
  selector:
    matchLabels:
      app: verifier-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: verifier-redis
    spec:
      containers:
      - image: redis:3.2
        imagePullPolicy: Always
        name: verfier-redis
        volumeMounts:
        - mountPath: /data
          name: redis-data
        ports:
        - containerPort: 6379
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: verifier-redis
