apiVersion: v1
kind: Service
metadata:
  name: verifier-redis-zmq
  namespace: athena
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: http
  selector:
    app: verifier-redis-zmq 
---
apiVersion: v1
kind: Service
metadata:
  name: verifier-router
  namespace: athena
spec:
  type: NodePort
  ports:
  - port: 5559
    targetPort: 5559
    name: front
    nodePort: 30559
  - port: 5560
    targetPort: 5560
    name: end
  selector:
    app: verifier-router
