apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: searcher
spec:
  selector:
    matchLabels:
      app: searcher
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: searcher
    spec:
      containers:
      - image: flylalala/searcher:cpu
        imagePullPolicy: Always
        name: searcher
        ports:
        - containerPort: 2333
---
apiVersion: v1
kind: Service
metadata:
  name: searcher-svc
spec:
  ports:
  - port: 2333
    targetPort: 2333
    name: http
  selector:
    app: searcher 
