apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-master
spec:
  ports:
  - port: 9333
    targetPort: 9333
    name: http
  selector:
    app: seaweedfs-master 
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-slave
spec:
  ports:
  - port: 58080
    targetPort: 58080
    name: http
  selector:
    app: swfs 
