apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: seaweedfs-master
spec:
  selector:
    matchLabels:
      app: seaweedfs-master
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: seaweedfs-master
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values: 
                    - swfs
              topologyKey: "kubernetes.io/hostname"
      containers:
      - image: xiongraorao/seaweedfs
        imagePullPolicy: Always
        name: seaweedfs
        volumeMounts:
        - mountPath: /data
          name: seaweedfs-master-data
        ports:
        - containerPort: 9333
        args: ['master']
      volumes:
      - name: seaweedfs-master-data
        persistentVolumeClaim:
          claimName: seaweedfs-master
