apiVersion: v1
kind: Service
metadata:
  name: mysql-master
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    name: http
  selector:
    app: mysql-master 
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    name: http
  selector:
    app: mysql-slave 
