apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-verifier-redis
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "verifier-redis"
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verifier-redis
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pv-verifier-redis
  resources:
    requests:
      storage: 10Gi
